In [1]:
from pathlib import Path

from docling.datamodel.base_models import InputFormat
from docling.datamodel.pipeline_options import PdfPipelineOptions
from docling.document_converter import DocumentConverter, PdfFormatOption
from docling_core.types.doc import DoclingDocument
from docling.datamodel.accelerator_options import AcceleratorDevice, AcceleratorOptions

ROOT = Path.cwd().parent                          # notebook lives in notebooks/
PDF = ROOT / "data" / "01_09_blueprints-visual-scripting_LQ.pdf"
PARSED = ROOT / "data" / "parsed"
PAGE_RANGE = (1, 580)
DOC_JSON = PARSED / f"blueprints_p{PAGE_RANGE[0]}-{PAGE_RANGE[1]}.json"


def convert_pdf() -> DoclingDocument:
    options = PdfPipelineOptions()
    options.do_ocr = False
    options.generate_picture_images = False
    options.accelerator_options = AcceleratorOptions(device=AcceleratorDevice.CUDA)
    converter = DocumentConverter(
        format_options={InputFormat.PDF: PdfFormatOption(pipeline_options=options)}
    )
    return converter.convert(PDF).document


def load_document() -> DoclingDocument:
    """Load the cached parse if it exists; otherwise convert once and cache it."""
    if DOC_JSON.exists():
        return DoclingDocument.load_from_json(DOC_JSON)
    doc = convert_pdf()
    PARSED.mkdir(parents=True, exist_ok=True)
    doc.save_as_json(DOC_JSON)
    return doc

In [4]:
doc = load_document()
print(DOC_JSON.name, "| tables:", len(doc.tables))

blueprints_p1-580.json | tables: 99

In [7]:
import re
def clean(text) -> str:
    text = str(text).replace("Downloaded from UnrealDocs.net", "")
    return re.sub(r"\s+", " ", text).strip()


def is_headerless(df) -> bool:
    """Docling names columns 0, 1, 2... when it found no header row."""
    return [str(c) for c in df.columns] == [str(i) for i in range(df.shape[1])]


def has_duplicate_header(df) -> bool:
    """First data row repeats the column names."""
    if len(df) == 0:
        return False
    return [clean(v) for v in df.iloc[0]] == [clean(c) for c in df.columns]


def same_header(df, ref) -> bool:
    """Header printed again on the new page: identical column names."""
    return [clean(c) for c in df.columns] == [clean(c) for c in ref.columns]

In [8]:
from docling_core.types.doc import DocItemLabel, TableItem

FURNITURE = {DocItemLabel.PAGE_HEADER, DocItemLabel.PAGE_FOOTER}

def content_before_tables(doc):
    """Map each table's ref -> True if real content sits between it and the previous table."""
    gap_before, gap = {}, True
    for item, _ in doc.iterate_items():
        if isinstance(item, TableItem):
            gap_before[item.self_ref] = gap
            gap = False
        elif getattr(item, "label", None) not in FURNITURE:
            gap = True                      # a title, paragraph, picture... anything real
    return gap_before

In [9]:
def stitch_tables(doc):
    gap_before = content_before_tables(doc)
    tables = []
    for t in doc.tables:
        if not t.prov:
            continue
        page, df = t.prov[0].page_no, t.export_to_dataframe(doc)

        if tables:
            prev = tables[-1]
            if (not gap_before[t.self_ref]                       # <-- new: nothing between them
                    and page == prev["pages"][-1] + 1
                    and df.shape[1] == prev["df"].shape[1]
                    and (is_headerless(df) or same_header(df, prev["df"]) or has_duplicate_header(df))):
                if has_duplicate_header(df):
                    df = df.iloc[1:]
                df = df.set_axis(prev["df"].columns, axis=1)
                prev["df"] = pd.concat([prev["df"], df], ignore_index=True)
                prev["pages"].append(page)
                continue

        tables.append({"df": df, "pages": [page]})
    return tables

In [17]:
from IPython.display import display

tables = stitch_tables(doc)
print(len(doc.tables), "fragments ->", len(tables), "tables")
for t in tables:
    print(t["pages"], t["df"].shape, list(t["df"].columns)[:3])
    display(t["df"])

99 fragments -> 89 tables
[136] (6, 2) ['Action', 'Command']

                           Action                     Command
0       Pin-specific Context Menu          Right-Click on Pin
1  Emphasize Connected WiresMouse              Hover over Pin
2          Connect to Another Pin    Left-Click + Drag to Pin
3    Filtered Action Menu for Pin  Left-Click + Drag to graph
4           Break All Connections     Alt + Left-Click on Pin
5            Move All Connections      Ctrl + LMB Drag to Pin

[184] (4, 3) ['Filter', 'Searchable Tags', 'Subfilters']

,Filter,Searchable Tags,Subfilters
0,Blueprint,Name ParentClass (Explicit) Path (Explicit) Interfaces (Explicit),Graphs Functions Macros EventGraphs Nodes Pins Variables/Properties Components
1,Graphs Functions Macros EventGraphs,Name Description,Nodes Pins Variables/Properties (for local variables)
2,Nodes,Name ClassName (Explicit) Comment,Pins
3,Pins Variables/Properties Components,Name DefaultValue IsArray (Explicit) IsReference (Explicit) IsSCSComponent (Explicit) PinCategory (Explicit),

[185] (1, 2) ['Filter Searchable Tags', 'Subfilters']

   Filter Searchable Tags Subfilters
0  ObjectClass (Explicit)

[198] (3, 2) ['Keyword', 'Description Exposes this class as an acceptable base class for']

,Keyword,Description Exposes this class as an acceptable base class for
0,Blueprintable,"creating Blueprints. The default is NotBlueprintable, unless inherited otherwise. This is inherited by subclasses."
1,BlueprintType,Exposes this class as a type that can be used for variables in Blueprints.
2,NotBlueprintable,Specifies that this class is NOT an acceptable base class for creating Blueprints. Negates the effect of a parent class having the Blueprintable keyword specified.

[199] (5, 2) ['Keyword', 'Description']

,Keyword,Description
0,BlueprintReadOnly,"This property can be read by blueprints, but not modified."
1,BlueprintReadWrite,This property can be read or written from a Blueprint.
2,Multicast Delegate Keywords,
3,BlueprintAssignable,Property should be exposed for assigning in Blueprints.
4,BlueprintCallable,Property should be exposed for calling in Blueprint graphs.

[201, 202] (7, 2) ['Keyword', 'Description']

,Keyword,Description
0,Blueprint to Native Communication,
1,BlueprintCallable,"This is a native function that can be called from a Blueprint, which executes native code that changes something about the object it is being called on, or some other global state. This means it has to be ""scheduled, "" or told explicitly the order in which it executes relative to other nodes. We do this by the white execution line. All Blueprint callable functions will be called in the order in which they along the white execution line."
2,BlueprintPure,"appear This is a native function that can be called from a Blueprint, which executes native code that does not change anything about the object it is being called on, or any other global state. This means that nothing is changed by calling this node, it just takes input, and tells you an output. These are things like math nodes (+, - , * , etc), or variable getters, or anything that does not change anything permanently. These do not need to be scheduled, and do not have a connection for the white execution line. They are automatically figured out by the compiler, based on which BlueprintCallable nodes need the data produced by these nodes."
3,Native to Blueprint Communication,
4,BlueprintImplementableEvent,This is the primary way we allow native functions to call up into Blueprints. They are like virtual functions that you implement in
5,,"the Blueprint themselves. If there is no implementation, the function call is ignored. It is important to note that if a BlueprintImplementableEvent does not have a return value or an out parameter, it will appear as an event, available by Right- clicking and selecting it in the event graph of the Blueprint. If it does have a return value or any out parameters, it will be listed in the My Blueprints tab, and can then be overridden by Right-clicking and selecting implement function. Note that BlueprintImplementableEvents do not have a native implementation of the function."
6,BlueprintNativeEvent,"These are the same as above, except there is a native default implementation of the function that is called if the Blueprint does not override the function. This is useful for things where you want some sort of default behavior if the Blueprint does not implement it, but want the Blueprint to be able to override the functionality if desired. These are more costly, so we only put them in where the functionality is needed. When you override the BlueprintNativeEvent, you can still call the native implementation, if desired, by Right-clicking on the event or function entry node, and selecting ""Add call to parent"" ."

[218, 219] (4, 2) ['Item', 'Description']

,Item,Description
0,Properties,
1,Comment Color,This allows you to change the background color of the comment box. Remember to use Alpha to adjust the transparency of the background.
2,Color Comment Bubble,"If this is checked, the Comment Color is applied to the comment box."
3,Move Mode,This allows you to set whether moving the comment also moves nodes within the comment (Group Movement) or whether the comment can be moved independently without affecting the nodes within it (Comment).

[257] (2, 1) ['Item Description']

                                                           Item Description
0                                                               Output Pins
1  Other ActorActor - This is the Actor that is overlapping this Blueprint.

[258] (2, 1) ['Item Description']

                                                           Item Description
0                                                               Output Pins
1  Other ActorActor - This is the Actor that is overlapping this Blueprint.

[259] (9, 2) ['Item', 'Description']

,Item,Description
0,Output Pins,
1,My Comp,PrimitiveComponent - The Component on the executing Actor that was hit.
2,Other,Actor - The other Actor involved in the collision.
3,Other Comp,PrimitiveComponent - The component on the other Actor involved in the collision that was hit.
4,Self Moved,"Boolean - Used when receiving a hit from another object's movement (if false), the directions of Hit Normal and Hit Impact Normal will be adjusted to indicate force from the other object against the object being hit."
5,Hit Location,Vector - The location of contact between the two colliding Actors.
6,Hit Normal,Vector - The direction of the collision.
7,Normal Impulse,Vector - The force that the Actors collided with.
8,Hit,"Struct HitResult - All the data collected in a Hit, you can pull off and ""break"" this result to gain access to the individual bits of data."

[260] (5, 2) ['Item', 'Description']

,Item,Description
0,Output Pins,Output Pins
1,Damage,Float - The amount of damage being passed into the Actor.
2,Damage Type,Object DamageType - This is the object that contains additional data on the Damage being dealt.
3,Instigated By,Controller - The Controller of the Object that is responsible for the damage. This could be the Player Controller that fired a gun or an AIController that threw the grenade to deal the damage.
4,Damage Causer,Actor - The Actor that caused the damage. This would be like a bullet or explosion.

[261] (10, 2) ['Item', 'Description']

,Item,Description
0,Output Pins,
1,Damage,Float - The amount of damage being passed into the Actor.
2,Damage Type,Object DamageType - This is the object that contains additional data on the Damage being dealt.
3,Hit Location,Vector - The location of where the damage is being applied.
4,Hit Normal,Vector - The direction of the collision.
5,Hit Component,PrimitiveComponent - The Component on the executing Actor that was hit.
6,Bone Name,Name - The name of the bone that was hit.
7,Shot from Direction,Vector - The direction the damage came from.
8,Instigated By,Actor - The Actor that is responsible for the damage. This would be the Actor that fired a gun or threw the grenade to deal the damage.
9,Damage Causer,Actor - The Actor that caused the damage. This would be like a bullet or explosion.

[262] (7, 2) ['Item', 'Description']

,Item,Description
0,Output Pins,
1,Damage Received,Float - The amount of damage received from the event.
2,Damage Type,Object DamageType - This is the object that contains additional data on the Damage being dealt.
3,Origin,Vector - This gives the location in 3D space where the damage originated.
4,Hit Info,"Struct HitResult - All the data collected in a Hit, you can pull off and ""break"" this result to gain access to the individual bits of data."
5,Instigated By,Controller - The Controller (AI or Player) that instigated the damage.
6,Damage Causer,"Actor - The Actor that caused the damage. Could be a bullet, rocket, laser, or a character punching another."

[265] (2, 2) ['Item', 'Description']

,Item,Description
0,Output Pins,
1,End Play Reason,enum EEndPlayReason - An enum indicating the reason for why Event End Play is being called.

[266] (2, 2) ['Item', 'Description']

,Item,Description
0,Output Pins,
1,Delta SecondsFloat - This outputs the amount of time between frames.,Delta SecondsFloat - This outputs the amount of time between frames.

[267] (3, 2) ['Item', 'Description']

          Item                                       Description
0  Output Pins                                       Output Pins
1       Size X   Int - The width of the render window in pixels.
2       Size Y  Int - The height of the render window in pixels.

[277] (3, 2) ['Setting', 'Description']

,Setting,Description
0,A setting of Public means that any other object can call this Function. This is the default setting.,Public
1,"Protected means that the Function can only be called by the current Blueprint, as well as any Blueprints that from the current Blueprint.",Protected A setting of derive
2,A setting of Private means that the Function can only be called from within the current Blueprint.,Private

[308] (1, 2) ['Node', 'Description']

,Node,Description
0,Request Content,"Attempts to download a manifest file using the specified manifest URL. On success, it will return an object that represents the remote content. This object can be queried for additional information, like total content size, download size, etc. The user can choose to download and install remote content."

[309] (2, 2) ['Node', 'Description']

,Node,Description
0,Get Disk Free Space,Gets the disk free space in megabytes where content is installed (or will be installed).
1,Get Required Disk Space,Gets the required disk space in megabytes for this content installation.

[310, 311] (6, 2) ['Node', 'Description']

,Node,Description
0,Get Download Size,Gets the total download size for this content installation.
1,Get Download Speed,Gets the current download speed in megabytes per second. Valid during installation.
2,Get Download Status Text,Gets the current installation status text. Valid during installation.
3,Get Install Progress,"Gets the current installation progress. The result is between 0 and 1 for known progress, or less than 0 for unknown progress."
4,Get Total Downloaded,Gets the total downloaded size in megabytes. Valid
5,Size,during installation.

[311] (2, 2) ['Node', 'Description']

,Node,Description
0,Get Installed Content,Gets the installed content. This will return a non-null object if there is installed content in the specified directory. The user can choose to mount installed content into the game.
1,Mount,Mounts installed content.

[312] (4, 2) ['Node', 'Description']

,Node,Description
0,Get Active Device Profile Name,Gets the name of the currently selected device profile name.
1,Get Installed Content Size,Gets the installed content size in megabytes
2,Get Supported Platform Names,"Gets the list of supported platform names on this device. Example: Android_ ETC2, Android_ ASTC"
3,Has Active WiFi Connection,Returns whether or not a WiFi connection is currently available.

[315] (7, 2) ['Function', 'Description']

,Function,Description
0,Random Bool from Stream,Outputs either 0 or 1 at random.
1,Random Float from Stream,"Outputs a random Float value in the range (0.0, 1.0)."
2,Random Float in Range from Stream,"Outputs a random Float value in the range (Min, Max)."
3,Random Integer From Stream,"Outputs a uniformly distributed random Integer value in the range (0, Max - 1)."
4,Random Integer In Range From Stream,"Outputs a random Integer value in the range (Min, Max)."
5,Random Rotator From Stream,Outputs a random Rotator value.
6,Random Unit Vector From Stream,Outputs a random unit-length Vector value.

[320, 321] (11, 1) ['Button/Checkbox Description']

                                                                                                        Button/Checkbox Description
0                                                        Adds a new float track to the Timeline, for animating scalar float values.
1                       Adds a new vector track to the Timeline, for animating float vector values such as rotation or translation.
2                         This adds an event track, which provides another execution output pin that will be triggered at keyframed
3                                                                                                               times on the track.
4                                                              Adds a new linear color track to the Timeline, for animating colors.
5        Add an external curve to the Timeline. This button is only active if an external curve is selected in the Content Browser.
6                                                                          Allows you to set the playback length for this Timeline.
7   If this is not active, the last keyframe of a sequence is ignored. This can help prevent skipping when an animation is looping.
8   If active, this Timeline node does not require an execution input to begin, and will start playing as soon as the level begins.
9                                 If active, the Timeline animation will repeat indefinitely unless stopped via the Stop input pin.
10                                                             If active, the Timeline animation will be replicated across clients.

[327] (4, 3) ['Name', 'Type', 'Description']

,Name,Type,Description
0,Inputs,,
1,Timeline Component,Takes in a Timeline variable.,Target
2,Outputs,,
3,Return Value,Float,Outputs the current playback rate for the Timeline.

[328] (4, 3) ['Name', 'Type', 'Description']

,Name,Type,Description
0,Inputs,,
1,Timeline Component,Takes in a Timeline variable.,Target
2,Outputs,,
3,Return Value,Float,Outputs the current playback position for the Timeline.

[328] (4, 3) ['Name', 'Type', 'Description']

,Name,Type,Description
0,Inputs,,
1,Timeline Component,Takes in a Timeline variable.,Target
2,Outputs,,
3,Return Value,Float,Outputs the total playback length for the Timeline.

[329] (4, 3) ['Name', 'Type', 'Description']

,Name,Type,Description
0,Inputs,,
1,Timeline Component,Takes in a Timeline variable.,Target
2,Outputs,,
3,Return Value,Boolean,Outputs the value of the Looping property.

[329] (4, 3) ['Name', 'Type', 'Description']

,Name,Type,Description
0,Inputs,,
1,Timeline Component,Takes in a Timeline variable.,Target
2,Outputs,,
3,Return Value,Boolean,Outputs whether the Timeline is currently playing.

[330] (4, 3) ['Name', 'Type', 'Description']

,Name,Type,Description
0,Inputs,,
1,Timeline Component,Takes in a Timeline variable.,Target
2,Outputs,,
3,Return Value,Boolean,Outputs whether the Timeline is currently reversing.

[330] (2, 3) ['Name', 'Type', 'Description']

     Name                Type                    Description
0  Inputs
1  Target  Timeline Component  Takes in a Timeline variable.

[331] (2, 3) ['Name', 'Type', 'Description']

     Name                Type                    Description
0  Inputs
1  Target  Timeline Component  Takes in a Timeline variable.

[331] (2, 3) ['Name', 'Type', 'Description']

     Name                Type                    Description
0  Inputs
1  Target  Timeline Component  Takes in a Timeline variable.

[332] (2, 3) ['Name', 'Type', 'Description']

     Name                Type                    Description
0  Inputs
1  Target  Timeline Component  Takes in a Timeline variable.

[332] (3, 3) ['Name', 'Type', 'Description']

,Name,Type,Description
0,Inputs,,
1,,Timeline Component Takes in a Timeline variable.,Target
2,New LoopingBoolean Used to set the Timeline's,New LoopingBoolean Used to set the Timeline's,looping value.

[333] (3, 3) ['Name', 'Type', 'Description']

,Name,Type,Description
0,Inputs,,
1,Target,Timeline Component Takes,in a Timeline variable.
2,New TimeFloat,New TimeFloat,Used to set a new playback position.

[333] (3, 3) ['Name', 'Type', 'Description']

            Name                Type                       Description
0         Inputs
1         Target  Timeline Component     Takes in a Timeline variable.
2  New RateFloat       New RateFloat  Used to set a new playback rate.

[334] (4, 3) ['Name', 'Type', 'Description']

,Name,Type,Description
0,Inputs,,
1,Timeline Component,Takes in a Timeline variable.,Target
2,Float,Used to jump to a new playback position.,New Position
3,Fire Events,Boolean,Used to control whether any events (from any Event Tracks) that were jumped will be fired.

[334] (2, 3) [0, 1, 2]

        0     1            2
0    Name  Type  Description
1  Inputs

[335] (2, 3) ['Name', 'Type', 'Description']

              Name                Type                         Description
0           Target  Timeline Component       Takes in a Timeline variable.
1  New LengthFloat     New LengthFloat  Used to set a new playback length.

[335] (3, 3) ['Name', 'Type', 'Description']

,Name,Type,Description
0,,,Inputs
1,Timeline Component,Takes in a Timeline variable.,Target
2,Byte,"Sets the playback mode to either ""Timeline Length"" or ""Last Keyframe. """,New Length Mode

[336] (2, 3) ['Name', 'Type', 'Description']

     Name                Type                    Description
0  Inputs
1  Target  Timeline Component  Takes in a Timeline variable.

[363] (3, 2) ['Blueprint Function Type', 'Description']

,Blueprint Function Type,Description
0,Object,Call on an object of the specified class that implements the interface.
1,Interface,Call on an object that implements this interface. Call on any object.
2,Message,"infoIf the object does not implement the correct interface, the function fails silently. This method is also slower than the object and interface methods."

[382, 383] (5, 2) ['Class Type', 'Description']

,Class Type,Description
0,Actor,An Actor is an object that can be placed or spawned in the world.
1,Pawn,"A Pawn is an Actor that can be ""possessed"" and receive input from a Controller."
2,"A Character is a Pawn that includes the ability to walk, run, jump, and more.",Character
3,A Player Controller is an Actor responsible for controlling a Pawn used by the player.,PlayerController
4,"Mode A Game Mode defines the game being played, its rules, scoring, and other faces of the game type.",Game

[402] (12, 3) ['Variable Type Color', 'Example', 'Represents']

,Variable Type Color,Example,Represents
0,Maroon,True or false value ( bool ).,Boolean
1,Sherpa blue,Whole number value between 0 and 255 ( unsigned char ).,Byte
2,Sea green,"Whole number value between -2,147,483,648 and 2,147,483,647 ( int ).",Integer
3,Moss green,"Whole number value between -9,223,372,036,854,775,808 and 9,223,372,036,854,775,807 ( long ).",Integer64
4,Yellow green,"Number value with a decimal such as 0.0553, 101.2887, and -78.322 ( float ).",Float
5,Mauve,Piece of text used to identify something in the game.,Name
6,Magenta,Group of alphanumeric characters such as Hello World ( string ).,String
7,Pink,Text that you display to users. Use this type for text that you want to localize.,Text
8,Gold,"Set of three numbers (X, Y, and Z). This type is useful for 3D coordinates and RGB color data.",Vector
9,Cornflower blue,Group of numbers that define rotation in 3D space.,Rotator
10,Orange,"Set of data that combines translation (3D position), rotation, and scale.",Transform
11,Blue,"Blueprint objects such as Lights, Actors, StaticMeshes, Cameras, and SoundCues.",Object

[414] (6, 2) ['Property', 'Description']

,Property,Description
0,Variable Set the variable whether or not,Type type in the dropdown menu and determine the variable is an array.
1,Instance Editable,Set whether or not it is possible to edit the value of the variable in the Class Defaults and the Blueprint's Details tab.
2,Tooltip,Set the tooltip for the variable.
3,Set whether or modified by,Private not this variable should be private and not derived Blueprints.
4,Category Choose from an name. Setting the Category appears in the Class Blueprint's Details,"existing category or type a new Category determines where the variable Defaults, the My Blueprint tab, and the tab."
5,Replication Choose if the replicated across should be a,"variable's value should or should not be clients, and if the value is replicated, if there notification by way of a callback function."

[414] (6, 2) ['Property', 'Description']

,Property,Description
0,Config Variable,Read its default value from a config file if it is present? Use this option to customize variable default values and behavior between different projects and configurations.
1,Transient,Not serialize and be zero-filled at load.
2,SaveGame,Be serialized for saved games.
3,Advanced Display,Be hidden in Class Defaults windows by default. Be capable of displaying multiple lines. To add a new line
4,Multi line,"while editing the variable, press Shift+Enter. info This option applies only to String and Text variables.\n\n<!-- image -->"
5,Deprecated,Be deprecated. Any nodes that reference the variable will produce a compiler warning indicating that it should be

[415] (1, 2) ['Property', 'Description']

,Property,Description
0,Deprecation Message,removed or replaced. (Optional) You can specify a message to include with the warning. For example: X is no longer supported. Please use Y instead.

[416] (3, 2) [0, 1]

                                                   0                    1
0  Shortcuts when dragging from the My Blueprint tab
1                                          Ctrl-drag  Creates a Get node.
2                                           Alt-drag  Creates a Set node.

[431] (1, 1) ['Action Command']

                            Action Command
0  Graph Action MenuRight-Click on a Graph

[431] (6, 2) ['Action', 'Command']

                        Action                       Command
0                  Select Node               Click on a Node
1             Add to Selection       Shift + Click on a Node
2             Toggle Selection        Ctrl + Click on a Node
3     Marquee Select (Replace)  Left Mouse Button (LMB) Drag
4         Marquee Select (Add)              Shift + LMB Drag
5  Marquee Select (Remove)Ctrl                    + LMB Drag

[431, 432] (7, 2) ['Action', 'Command']

                      Action                  Command
0              Pan the Graph                 RMB Drag
1  Zoom to fit SelectionHome
2                Zoom In/Out      Mouse Wheel Up/Down
3                Zoom In/Out  Hold LMB + RMB and Drag
4         Zoom In Beyond 1:1              Ctrl + Zoom
5        Go into Child Graph                   PageDn
6         Go to Parent Graph                   PageUp

[432] (7, 2) ['Action', 'Command']

                        Action           Command
0  Find in Content BrowserCtrl               + B
1               Save Blueprint          Ctrl + S
2                         Redo          Ctrl + Y
3                         Undo          Ctrl + Z
4       Find in this Blueprint          Ctrl + F
5        Find in any Blueprint  Ctrl + Shift + F
6        Compile the Blueprint                F7

[433] (6, 2) ['Action', 'Command']

                                       Action                      Command
0                      Get/Set as appropriate   LMB Drag to Compatible Pin
1                          Get/Set (via Menu)          LMB Drag into Graph
2                                Get Variable   Ctrl + LMB Drag into Graph
3                                Set Variable    Alt + LMB Drag into Graph
4                        Change Existing Node  LMB Drag to edge of Get/Set
5  Change Category/Reorder LMB Drag inside My                    Blueprint

[433, 434] (14, 2) ['Action', 'Command']

                             Action                          Command
0        Node-specific Context Menu            Right-Click on a Node
1       Go to Associated Node/Graph      Double Left-Click on a Node
2                        Move Nodes               LMB Drag on a Node
3               Move Selected Nodes                       Arrow Keys
4             Delete Selected Nodes                           Delete
5          Rename Node/Edit Comment          Left-Click on the Title
6          Rename Node/Edit Comment                               F2
7                 Toggle Breakpoint                               F9
8             Clear All Breakpoints                Ctrl + Shift + F9
9                     Cut Selection                         Ctrl + X
10                   Copy Selection                         Ctrl + C
11                      Paste Nodes                         Ctrl + V
12              Duplicate Selection                         Ctrl + D
13  Add a Comment Around SelectionC  Add a Comment Around SelectionC

[434] (6, 2) ['Action', 'Command']

                         Action                     Command
0     Pin-specific Context Menu          Right-Click on Pin
1           Emphasize Connected   WiresMouse Hover over Pin
2        Connect to Another Pin    Left-Click + Drag to Pin
3  Filtered Action Menu for Pin  Left-Click + Drag to graph
4         Break All Connections     Alt + Left-Click on Pin
5          Move All Connections      Ctrl + LMB Drag to Pin

[435] (10, 2) ['Action', 'Command']

                Action         Command
0          Branch Node  B + Left-Click
1     Comment Box Node               C
2           Delay Node  D + Left-Click
3        Sequence Node  S + Left-Click
4            Gate Node  G + Left-Click
5  For-Each Loop NodeF    + Left-Click
6      Multi-gate Node  M + Left-Click
7      Do N Times Node  N + Left-Click
8         Do Once Node  O + Left-Click
9      BeginPlay Event  P + Left-Click

[440] (6, 2) ['Item', 'Description']

,Item,Description
0,Input Pins,
1,(Unlabeled),This execution input triggers the branch check.
2,Condition,Takes in a boolean value used to indicate which output pin will be triggered.
3,Output Pins,
4,True,This outputs an execution pulse if the incoming condition was true .
5,False,This outputs an execution pulse if the incoming condition was false .

[441] (6, 2) ['Item', 'Description']

,Item,Description
0,Input Pins,
1,Enter,This execution input triggers the DoN check.
2,n,This input sets the number of times the DoN node will trigger.
3,Reset,This execution input will reset the DoN node so that it can be triggered again.
4,Output Pins,
5,Exit,"This execution pin is only triggered if the DoN has not yet been triggered more than N times, or if its Reset input has been called."

[442] (5, 2) ['Item', 'Description']

,Item,Description
0,Input Pins,
1,(Unlabeled),This execution input triggers the DoOnce check.
2,Reset,This execution input will reset the DoOnce node so that it can be triggered again.
3,Output Pins,
4,Completed,"This execution pin is only triggered if the DoOnce has not yet been triggered, or if its Reset input has been called."

[443] (6, 2) ['Item', 'Description']

,Item,Description
0,Input Pins,
1,(Unlabeled),This execution input triggers the FlipFlop.
2,Output Pins,
3,A,This output pin is called the first and every odd-numbered time thereafter that the FlipFlop is triggered.
4,B,This output pin is called the second and every even-numbered time thereafter that the FlipFlop is triggered.
5,Is A,"Outputs a boolean value indicating whether Output A is being triggered or not. This, in effect, will toggle between true and false each time the FlipFlop node is triggered."

[444] (8, 2) ['Item', 'Description']

,Item,Description
0,Input Pins,
1,(Unlabeled),This execution input launches the loop.
2,First Index,Takes in an Int representing the first index of the loop.
3,Last Index,Takes in an Int representing the last index of the loop.
4,Output Pins,
5,Loop Body,This outputs an execution pulse on each iteration of the loop as it moves between the indices.
6,Index,This outputs the current index of the loop.
7,Completed,This is a standard execution output pin that fires when the for loop has completed.

[445] (5, 2) ['Item', 'Description']

          Item                                                Description
0   Input Pins
1  (Unlabeled)                    This execution input launches the loop.
2  First Index  Takes in an Int representing the first index of the loop.
3   Last Index   Takes in an Int representing the last index of the loop.
4        Break                      This execution input breaks the loop.

[446] (4, 1) ['Item Description']

                                                                                           Item Description
0                                                                                               Output Pins
1  Loop Body This outputs an execution pulse on each iteration of the loop as it moves between the indices.
2                                                         Index This outputs the current index of the loop.
3             Completed This is a standard execution output pin that fires when the for loop has completed.

[447] (8, 2) ['Item', 'Description']

,Item,Description
0,Input Pins,
1,Enter,This execution input represents any execution that is to be controlled by the gate.
2,Open,"This execution pin sets the state of the gate to open, allowing execution pulses to pass through to the Exit output pin."
3,Close,"This execution pin sets the state of the gate to closed, stopping execution pulses from passing through to the Exit output pin."
4,Toggle,This execution pin reverses the current state of the gate. Open becomes closed and vice versa.
5,Start Closed,This boolean input determines the starting status of the gate. If set to true the gate begins in a closed state.
6,Output Pins,
7,Exit,"If the gate status is currently open, then any execution pulses that hit the Enter input pin will cause a pulse to leave the Exit output pin. If the gate is closed, the Exit pin is nonfunctional."

[448] (2, 2) [0, 1]

            0            1
0        Item  Description
1  Input Pins

[449] (8, 2) ['Item', 'Description']

,Item,Description
0,,(Unlabeled) This is the primary execution input that takes in any pulses that need to be routed by this MultiGate.
1,Reset,"This sets the current output index back to 0 by default, or to the currently set Start Index, if not -1."
2,Is Random,"If set to true, then the outputs are chosen in random order."
3,Loop,"If set to true, then the outputs will continuously repeat in a loop. If false, then the MultiGate ceases to function once all outputs have been used."
4,Start,Index Takes in an Int to represent the output index the MultiGate should use first. A value of -1 is the same as not specifying a start point.
5,Output Pins,
6,Out #,Each output represents a possible output pin that the MultiGate may use to send out a routed execution pulse.
7,Add pin,"Though not really an output pin, this button allows you to add as many outputs as you like. Outputs can be removed by right- clicking and choosing Remove Output Pin."

[450] (5, 2) ['Item', 'Description']

,Item,Description
0,Input Pins,
1,(Unlabeled),This is the primary execution input that takes in any pulses that need to be routed by this Sequence.
2,Output Pins,
3,Out #,Each output represents a possible output pin that the Sequence may use to send out a routed execution pulse.
4,Add pin,"Though not really an output pin, this button allows you to add as many outputs as you like. Outputs can be removed by right- clicking and choosing Remove Output Pin."

[451] (6, 2) ['Item', 'Description']

,Item,Description
0,Input Pins,
1,(Unlabeled),This is the primary execution input that takes in any pulses that will drive this WhileLoop.
2,Condition,This is the loop's test condition.
3,Output Pins,
4,Loop Body,This outputs an execution pulse on each iteration of the loop as it moves between the indices.
5,Completed,This is a standard execution output pin that fires as soon as the loop ends.

[470] (5, 2) ['Blueprint', 'Description']

,Blueprint,Description
0,Character (1),Here the Get Player Character node is used and we are casting to a Character Blueprint called MyCharacter.
1,PlayerController (2),Here the Get Player Controller node is used and we are casting to a Player Controller Blueprint called MyController.
2,Game Mode (3),Here the Get Game Mode node is used and we are casting to a Game Mode Blueprint called MyGame.
3,Pawn (4),Here the Get Controlled Pawn and Get Player Controller nodes are used to cast to a Pawn Blueprint called MyPawn.
4,HUD (5),Here the Get HUD and Get Player Controller nodes are used to cast to a HUD Blueprint called MyHUD.

[512] (3, 2) ['Sort Method', 'Description']

,Sort Method,Description
0,None,Properties appear in the same order as they appear in the Blueprint class.
1,Sort By Access Specifier,"Properties are grouped together by Access Specifiers in order of visibility(public, protected, private.)"
2,Sort For Optimal Padding,Properties are sorted to minimize padding in the compiled class layout.

[521, 522] (6, 2) ['Item', 'Description']

,Item,Description
0,Default,Lists any variables and their values if you do not specify a different category than Default when you create them. Note that you must compile the Blueprint in order to display its variables on the Class Defaults tab.
1,Rendering,Contains information about properties related to how (and whether) an Actor based on the Blueprint is rendered in the game.
2,ReplicationContains,"information about properties that dictate how your Actor behaves in a networked game, such as its network"
3,,priority and relevancy to other clients.
4,Input,Contains information about how Actors based on this Blueprint respond to input.
5,Actor,"Contains information about Actors based on this Blueprint, such as whether they can be damaged. Note that for Level Blueprints, only the Tags properties are relevant in this section."

[528] (4, 3) ['Color', '', 'Description']

,Color,,Description
0,Red,Something on the left panel is missing on the right (subrtraction.),
1,Green,Something on the right panel is missing on the left (addition.),
2,Cyan,Something has changed.,
3,Grey,"Something on the left panel is missing on the right(moved nodes, comments.)",

[540] (5, 2) ['Default Visible UI ComponentsAvailable in the Window Menu', 'Default Visible UI ComponentsAvailable in the Window Menu']

,Default Visible UI ComponentsAvailable in the Window Menu,Default Visible UI ComponentsAvailable in the Window Menu
0,1. Menu,Debug
1,2. Toolbar,Compiler Results
2,3. Components,Find Results
3,4. My Blueprint,Viewport
4,5. Graph Editor,

[544] (1, 2) [0, 1]

,0,1
0,1. Menu 2. Toolbar 3. My Blueprint 4. Details 5. Graph Editor,Debug Compiler Results Find Results

[547] (5, 2) [0, 1]

                 0                 1
0          1. Menu  Compiler Results
1       2. Toolbar             Debug
2  3. My Blueprint      Find Results
3       4. Details           Palette
4  5. Graph Editor          Viewport

[549] (1, 2) ['Default Visible UI ComponentsAvailable in the Window Menu', 'Default Visible UI ComponentsAvailable in the Window Menu']

,Default Visible UI ComponentsAvailable in the Window Menu,Default Visible UI ComponentsAvailable in the Window Menu
0,1. Menu 2. Toolbar 3. My Blueprint 4. Details 5. Graph Editor,Debug Find Results Palette

[563] (12, 2) ['Control', 'Action']

,Control,Action
0,Right-Click + Drag,Pans the Graph.
1,Mouse Scroll,Zooms the Graph.
2,Right-Click,Brings up context menu.
3,Click on node,Selects the node.
4,Click + Drag in empty space,Selects the nodes inside the marquee select box.
5,Ctrl + Click + Drag in empty space,Toggles selection of the nodes inside the marquee select box.
6,Shift + Click + Drag in empty space,Adds the nodes inside the marquee select box to the current selection.
7,Click + Drag on node,Move node.
8,Click + Drag from pin to pin,Wires the pins together.
9,Ctrl + Click + Drag from pin to pin,Moves wires from origin pin to destination pin.
10,Click + Drag from pin to empty space,Brings up context menu showing only relevant nodes. Wires the original pin to a compatible pin on the created node.
11,Alt + Click on a pin,Remove all wires connected to the selected pin.

[565] (12, 2) ['Command', 'Description']

,Command,Description
0,Load and Save,
1,Save,Saves the Blueprint.
2,Open Asset...,Summons the asset picker window.
3,Save All,Saves all unsaved levels and assets.
4,Choose Files to Save...,Opens a dialog with save options for content and levels.
5,Connect to Source Control...,"If Source Control is enabled, opens a dialog with check- in options for content and levels."
6,Blueprint,
7,Compile,Compiles the Blueprint.
8,Refresh All Nodes,Refreshes all nodes in the graph to account for external changes.
9,Reparent Blueprint,Change the parent of the open Blueprint.
10,Diff,Diff against previous revisions. Requires source control to be active.
11,Developer,"Open the Developer Menu, where you can change compiler settings and recompile modules like the Graph Editor."

[566] (12, 2) ['Command', 'Description']

,Command,Description
0,History,
1,Undo,Undo the last action.
2,Redo,Redo the last undone action.
3,Undo History,Displays the entire Undo History.
4,Search,
5,Search,"Find references to functions, events, variables, and pins in the current Blueprint."
6,Find in Blueprints,"Find references to functions, events, variables, and pins in ALL Blueprints."
7,Delete Unused Variables,Deletes any variables that are never used.
8,Configuration,
9,Editor Preferences,Opens the settings for the Editor.
10,Project Settings,Opens the settings for the current project.
11,Plugins,Opens the Plugin Browser tab.

[566] (3, 2) [0, 1]

,0,1
0,Find in Content Browser...,Summons the Content Browser and navigates to this asset.
1,Reference Viewer...,Launches the reference viewer to show what the current asset references and what references the current asset.
2,Size Map...,Displays an interactive map showing the approximate size of this asset and everything it references.

[566, 567] (7, 2) ['Command', 'Description']

,Command,Description
0,Pin Visibility,
1,Show All Pins,Shows all pins on all nodes.
2,Hide Unused Pins,Hides all pins with no connections and no default values.
3,Hide Unconnected Pins,Hides all pins with no connections. This option will hide input pins for inputs that have been set directly on the node.
4,Zoom,
5,Zoom to Graph Extents,Fits the current view to the entire graph.
6,Zoom to Selection,Fits the current view to the selection.

[567] (6, 2) ['Command', 'Description']

,Command,Description
0,Breakpoints,
1,Disable All Breakpoints,Disables all breakpoints in all graphs of the current Blueprint or Level Blueprint.
2,Enable All Breakpoints,Enables all breakpoints in all graphs of the current Blueprint or Level Blueprint.
3,Delete All Breakpoints,Removes all breakpoints in all graphs of the current Blueprint or Level Blueprint.
4,Watches,
5,Delete All Watches,Removes all watch values in all graphs of the current Blueprint or Level Blueprint.

[567, 568] (16, 2) ['Command', 'Description']

,Command,Description
0,Toolbar,Shows the Toolbar if it is currently not visible.
1,Details,Shows the Details pane if it is currently not visible.
2,Debug,Shows the Debug pane if it currently not visible.
3,Palette,Shows the Blueprint Editor Palette pane if it is not currently visible.
4,My Blueprint,Shows the Blueprint Editor My Blueprint Panel pane if it is not currently visible.
5,Compiler Results,Shows the Compiler Results pane if it is not currently visible.
6,Find Results,Shows the Find Results pane if it is not currently visible.
7,Components,Shows the Components panel if it is not currently visible.
8,Viewport,Shows the Preview Viewport pane if it is not currently visible.
9,Content Browser,Opens a sub-menu with access to all four Content Browsers.
10,Developer Tools,"Blueprint Debugger: Opens the Blueprint Debugger, which shows you the current ""stack"" of commands that is being run in a Blueprint along with all watched values. Collision Analyzer: Shows the Collision Analyzer. Debug Tools: Show the Debug Tools panel, which contains an assortment of functions for common debug tasks (reloading textures, showing texture atlases, gamma correction, etc...) Message Log: Opens the Message Log. This is where errors or warnings from the Editor will go. Output Log: Opens the Output Log. If you are debugging something using Print it will appear here. Visual Logger: Opens the Visual Logger. Class Viewer: Opens the Class Viewer. Device Manager: Opens the Device Manager. Device Profiles: Opens the Device Profiles Tab. Session Frontend: Shows the Session Frontend. Please see the Unreal Frontend documentation for more information. Widget Reflector: Opens the Widget Reflector. This enables you to see the various Slate elements that make up the interfaces within the Editor interface."
11,Project Launcher,Shows the Project Launcher which enables you to run your project on any appropriately setup and connected devices.
12,Plugins,Shows the Plugin Tab where you can load/unload plugins.
13,Reset Layout...,"Restores the default layout for the entire Unreal Engine 4 Editor. This requires the Editor to restart, but it will re-open the current project."
14,Save Layout,Saves the current interface layout.
15,Enable Fullscreen,Enables fullscreen mode for the Main Editor window.

[570] (5, 3) ['Button', 'Name', 'Description']

,Button,Name,Description
0,,New Variable,"Creates a new variable when clicked. The properties of that variable immediately appear in the Details tab. There, you can change the name, type, and other properties."
1,,New Function,"Creates a new function, then immediately puts focus on the Name field of the Details tab so that it can be named. A new graph view will also be opened where you can define the node network for the function."
2,,New Macro,"Creates a new macro, then immediately puts focus on the Name field of the Details tab so that it can be named. A new graph view will also be opened where you can define the node network for the macro."
3,,New Event Graph,"Creates a new function, then immediately puts focus on the Name field of the Details tab so that it can be named. The new graph appears and is ready to have a node network defined within it."
4,,New Event Dispatcher,"Creates a new event dispatcher, then immediately puts focus on the Name field of the Details tab so that it can be named."

[576] (1, 2) ['Button', 'Description']

,Button,Description
0,,Compilation was successful. Clicking the button compiles the Blueprint being edited. Output from the compiling process is displayed in the Blueprint Log of the Message Log. This button will be inactive during debugging.

[577] (13, 2) ['Button', 'Description']

,Button,Description
0,,The Blueprint needs to be recompiled. Clicking the button compiles the Blueprint being edited. Output from the compiling process is displayed in the Blueprint Log of the Message Log. This button will be inactive during debugging.
1,,There was a warning during compilation. Clicking the button compiles the Blueprint being edited. Output from the compiling process is displayed in the Blueprint Log of the Message Log. This button will be inactive during debugging.
2,,Compilation failed. Clicking the button compiles the Blueprint being edited. Output from the compiling process is displayed in the Blueprint Log of the Message Log. This button will be inactive during debugging.
3,,Saves the current Blueprint.
4,,Summons the Content Browser and navigates to this asset.
5,,"Finds references to functions, events, variables, and pins in the current Blueprint."
6,,Opens the Blueprint Properties in the Details pane.
7,,Shows the Class Defaults Panel in the Details Tab
8,,Starts the game in simulation mode. See the Simulate In Editor section for more information.
9,,Starts the game in normal play mode. Clicking the arrow displays the Play Options menu. See the Play In Editor section for more information.
10,,"Pauses simulation. When the simulation is paused, the Resume and Frame Skip buttons will appear on the toolbar."
11,,Resumes execution after a breakpoint is hit or the Pause button is pressed.
12,,"Advances a single frame, or tick. This button appears when simulation is paused, or when a breakpoint is hit."

[578] (5, 2) ['Button', 'Description']

,Button,Description
0,,Halts execution of the game and exits Simulate In Editor mode.
1,,"Switches from Simulate In Editor mode to Play In Editor mode. Attaches to the player controller, allowing normal gameplay controls. Toggles with Eject."
2,,"Switches from Play In Editor mode to Simulate In Editor mode. Detaches from the player controller, allowing regular editor controls. Toggles with Possess."
3,,Steps through execution of the graph one node at a time. This button appears during simulation after a breakpoint is hit.
4,,"If you have one or more instances of a Blueprint in a level, this dropdown allows you to select which instance to debug."

[580] (4, 2) ['Item', 'Description']

,Item,Description
0,Reset Camera Refocuses the camera,on the components.
1,Toggles realtime rendering of the viewport.,Realtime
2,Toggles whether a floor is displayed to assist with the placement of components.,Show Floor
3,Toggles viewport grid.,Show Grid

## Table context: heading path + preceding text

Keyed by the table fragment's `self_ref`, so a stitched table keeps the context of
its first fragment.

In [11]:
from docling_core.types.doc import DocItemLabel, TableItem

TEXT_LABELS = {
    DocItemLabel.TEXT, DocItemLabel.PARAGRAPH, DocItemLabel.LIST_ITEM,
    DocItemLabel.CAPTION, DocItemLabel.FOOTNOTE, DocItemLabel.CODE,
}
MAX_ABOVE_TEXTS = 3
MAX_ABOVE_CHARS = 600


def squash(text: str) -> str:
    """Collapse whitespace so context stays compact in the prompt."""
    return re.sub(r"\s+", " ", text).strip()


def table_contexts(doc):
    """Map each table fragment ref -> {"headings", "above"} in reading order."""
    contexts, heading_stack, buffer = {}, [], []
    for item, _ in doc.iterate_items():
        label = getattr(item, "label", None)
        if label in FURNITURE:
            continue
        if isinstance(item, TableItem):
            contexts[item.self_ref] = {
                "headings": " > ".join(text for _, text in heading_stack),
                "above": " ".join(buffer[-MAX_ABOVE_TEXTS:])[-MAX_ABOVE_CHARS:],
            }
            buffer = []
        elif label == DocItemLabel.SECTION_HEADER:
            while heading_stack and heading_stack[-1][0] >= item.level:
                heading_stack.pop()
            heading_stack.append((item.level, squash(item.text)))
            buffer = []
        elif label in TEXT_LABELS:
            buffer.append(squash(item.text))
    return contexts

## Table -> JSON

Headerless tables (columns literally named 0, 1, 2...) export `columns: None`.

In [12]:
def cell_text(value) -> str:
    """DataFrame cell -> string; missing values become empty strings."""
    if value is None or (isinstance(value, float) and pd.isna(value)):
        return ""
    return str(value).strip()


def table_json(df) -> dict:
    """Structured copy of a table: {"columns": [...] | None, "rows": [[...], ...]}."""
    columns = None if is_headerless(df) else [str(c) for c in df.columns]
    return {"columns": columns,
            "rows": [[cell_text(v) for v in row] for row in df.itertuples(index=False)]}


def rows_as_text(table: dict) -> str:
    """Plain-text rendering of the rows, used for embed and return text."""
    lines = []
    for row in table["rows"]:
        if table["columns"] is None:
            lines.append(" | ".join(row))
        else:
            lines.append("; ".join(f"{name}: {value}" for name, value in zip(table["columns"], row)))
    return "\n".join(lines)

## Local-LLM summary (Ollama)

Gemma has no reliable system role, so everything goes in one user message.
Summaries are cached by prompt hash: each table is only run once.

In [13]:
import hashlib
import json

from pathlib import Path



import ollama



MODEL = "gemma2:2b"

MAX_TABLE_CHARS = 6000

MIN_ROWS_TO_SUMMARIZE = 3

SUMMARY_CACHE = Path("..") / "data" / "parsed" / "table_summaries.json"

OLLAMA_OPTIONS = {"temperature": 0, "num_predict": 256}



INSTRUCTIONS = (

    "You are summarizing one table from the Unreal Engine documentation. "

    "Write 2-3 sentences on what the table documents and what a reader could look "

    "up in it. Copy node, pin and checkbox names exactly as written. Use only the "

    "table and the context below; add nothing else. No preamble, no bullet points."

)





def load_summaries() -> dict:

    if SUMMARY_CACHE.exists():

        return json.loads(SUMMARY_CACHE.read_text(encoding="utf-8"))

    return {}





def save_summaries(cache: dict) -> None:

    SUMMARY_CACHE.parent.mkdir(parents=True, exist_ok=True)

    SUMMARY_CACHE.write_text(json.dumps(cache, indent=2, ensure_ascii=False), encoding="utf-8")





def prompt_key(prompt: str) -> str:

    return hashlib.sha256(prompt.encode("utf-8")).hexdigest()





def fit_table(table: dict, limit: int):

    """Keep only the leading rows that fit the context budget; report truncation."""

    if len(json.dumps(table, ensure_ascii=False)) <= limit:

        return table, False

    rows = []

    for row in table["rows"]:

        if len(json.dumps({"columns": table["columns"], "rows": rows + [row]}, ensure_ascii=False)) > limit:

            break

        rows.append(row)

    return {"columns": table["columns"], "rows": rows}, True





def build_prompt(table: dict, headings: str, above: str) -> str:

    return (

        f"{INSTRUCTIONS}\n\n"

        f"Section: {headings or '(none)'}\n"

        f"Text above the table: {above or '(none)'}\n\n"

        f"Table JSON:\n{json.dumps(table, ensure_ascii=False)}"

    )





def summarize_table(table: dict, headings: str, above: str, cache: dict) -> dict:

    """Return {"summary", "summary_truncated"}, memoized in cache by prompt hash."""

    if not table["rows"] or len(table["rows"]) <= MIN_ROWS_TO_SUMMARIZE:

        return {"summary": None, "summary_truncated": False}



    fitted, truncated = fit_table(table, MAX_TABLE_CHARS)

    prompt = build_prompt(fitted, headings, above)

    key = prompt_key(prompt)

    if key not in cache:

        response = ollama.chat(

            model=MODEL,

            messages=[{"role": "user", "content": prompt}],

            options=OLLAMA_OPTIONS,

        )

        cache[key] = response["message"]["content"].strip()

        save_summaries(cache)

    return {"summary": cache[key], "summary_truncated": truncated}

## Build records

In [14]:
def table_record(df, pages, headings, above, summary) -> dict:
    """One retrievable record per table."""
    table = table_json(df)
    raw_rows = rows_as_text(table)
    parts = [part for part in (headings, above, summary["summary"], raw_rows) if part]
    without_summary = [part for part in (headings, above, raw_rows) if part]
    return {
        "pages": list(pages),
        "headings": headings,
        "above": above,
        "summary": summary["summary"],
        "summary_truncated": summary["summary_truncated"],
        "table": table,
        "embed_text": "\n\n".join(parts),
        "return_text": "\n\n".join(without_summary),
    }


def attach_context(tables, contexts, cache) -> list:
    """Walk stitched tables in order; each consumes as many fragments as it spans pages."""
    records, fragment = [], 0
    for entry in tables:
        context = contexts.get(doc.tables[fragment].self_ref, {"headings": "", "above": ""})
        summary = summarize_table(table_json(entry["df"]), context["headings"], context["above"], cache)
        records.append(table_record(entry["df"], entry["pages"],
                                    context["headings"], context["above"], summary))
        fragment += len(entry["pages"])
    return records

In [15]:
contexts = table_contexts(doc)
cache = load_summaries()
records = attach_context(tables, contexts, cache)
print(len(records), "records;",
      sum(1 for r in records if r["summary"]), "summarized;",
      sum(1 for r in records if r["summary_truncated"]), "truncated")

89 records; 57 summarized; 0 truncated

## Verify

One merged table, one headerless, one skipped-small, one truncated (if any), one regular.

In [16]:
def pick(predicate):
    """First record matching predicate that has not been shown yet."""
    return next((r for r in records if id(r) not in seen and predicate(r)), None)


seen = set()
samples = [
    ("merged across pages", lambda r: len(r["pages"]) > 1),
    ("headerless", lambda r: r["table"]["columns"] is None),
    ("skipped small", lambda r: r["summary"] is None),
    ("truncated", lambda r: r["summary_truncated"]),
    ("regular", lambda r: r["table"]["columns"] is not None
     and len(r["table"]["rows"]) > MIN_ROWS_TO_SUMMARIZE),
]

for label, predicate in samples:
    record = pick(predicate)
    if record is None:
        print(f"--- {label}: none in this range ---")
        continue
    seen.add(id(record))
    print(f"--- {label} ---")
    print(json.dumps(record, indent=2, ensure_ascii=False)[:1500])

--- merged across pages ---
{
  "pages": [
    201,
    202
  ],
  "headings": "Executable and Overridable Functions",
  "above": "UPARAM() to change the display name of a pin. For example, the MakeRotator function in KismetMathLibrary uses UPARAM() and the DisplayName keyword to change how the Roll, Pitch, and Yaw parameters appear in Blueprints. /** Makes a rotator {Roll, Pitch, Yaw} from rotation values supplied in degrees */ UFUNCTION(BlueprintPure, Category=\"Math|Rotator\" , meta= (Keywords=\"construct build rotation rotate rotator makerotator\" NativeMakeFunc)) static FRotator MakeRotator( UPARAM(DisplayName=\"X (Roll)\") float Roll, UPARAM(DisplayName=\"Y (Pitch)\") float Pitch, UPARAM(DisplayName=\"Z (Yaw)\") float Yaw); ,",
  "summary": "This table describes different types of functions that can be used in Unreal Engine Blueprints, including how they communicate with native code.  Readers can look up specific keywords like \"BlueprintPure\" and \"BlueprintCallable\" to understand the function's purpose and execution within a Blueprint.",
  "summary_truncated": false,
  "table": {
    "columns": [
      "Keyword",
      "Description"
    ],
    "rows": [
      [
        "Blueprint to Native Communication",
        ""
      ],
      [
        "BlueprintCallable",
        "This is a native function that can be called from a Blueprint, which executes native code that changes something about the object it is being called on, or some other global state. This means it has to be \"scheduled, \" or tol
--- headerless ---
{
  "pages": [
    334
  ],
  "headings": "Set Timeline Length",
  "above": "The Set Timeline Length node sets the length of the Timeline's total playback.",
  "summary": null,
  "summary_truncated": false,
  "table": {
    "columns": null,
    "rows": [
      [
        "Name",
        "Type",
        "Description"
      ],
      [
        "Inputs",
        "",
        ""
      ]
    ]
  },
  "embed_text": "Set Timeline Length\n\nThe Set Timeline Length node sets the length of the Timeline's total playback.\n\nName | Type | Description\nInputs |  | ",
  "return_text": "Set Timeline Length\n\nThe Set Timeline Length node sets the length of the Timeline's total playback.\n\nName | Type | Description\nInputs |  | "
}
--- skipped small ---
{
  "pages": [
    185
  ],
  "headings": "Advanced Search Syntax",
  "above": "",
  "summary": null,
  "summary_truncated": false,
  "table": {
    "columns": [
      "Filter Searchable Tags",
      "Subfilters"
    ],
    "rows": [
      [
        "ObjectClass (Explicit)",
        ""
      ]
    ]
  },
  "embed_text": "Advanced Search Syntax\n\nFilter Searchable Tags: ObjectClass (Explicit); Subfilters: ",
  "return_text": "Advanced Search Syntax\n\nFilter Searchable Tags: ObjectClass (Explicit); Subfilters: "
}
--- truncated: none in this range ---
--- regular ---
{
  "pages": [
    136
  ],
  "headings": "Pin Actions",
  "above": "There are some additional pin related actions that can be taken for nodes as outlined in the table below.",
  "summary": "This table describes various actions that can be performed on pins within the Unreal Engine, allowing users to interact with them in different ways.  Readers can find information about right-clicking on pins for context menus, hovering over pins for emphasis, connecting pins to other pins, and more.",
  "summary_truncated": false,
  "table": {
    "columns": [
      "Action",
      "Command"
    ],
    "rows": [
      [
        "Pin-specific Context Menu",
        "Right-Click on Pin"
      ],
      [
        "Emphasize Connected WiresMouse",
        "Hover over Pin"
      ],
      [
        "Connect to Another Pin",
        "Left-Click + Drag to Pin"
      ],
      [
        "Filtered Action Menu for Pin",
        "Left-Click + Drag to graph"
      ],
      [
        "Break All Connections",
        "Alt + Left-Click on Pin"
      ],
      [
        "Move All Connections",
        "Ctrl + LMB Drag to Pin"
      ]
    ]
  },
  "embed_text": "Pin Actions\n\nThere are some additional pin related actions that can be taken for nodes as outlined in the table below.\n\nThis table describes various actions that can be performed on pins within the Unreal Engine, allowing users to interact with them in different ways.  Readers can find information about right-clicking on pins for context menus, ho